/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as FindTutorRouteImport } from './routes/find-tutor'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as TutorTutorIdRouteImport } from './routes/tutor.$tutorId'
import { Route as SettingsVerificationRouteImport } from './routes/settings.verification'
import { Route as SessionsIdRouteImport } from './routes/sessions.$id'
import { Route as PathwiseDemoRouteImport } from './routes/pathwise.demo'
import { Route as OnboardingTutorRouteImport } from './routes/onboarding.tutor'
import { Route as OnboardingStudentRouteImport } from './routes/onboarding.student'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardMessagesRouteImport } from './routes/dashboard.messages'
import { Route as DashboardEarningsRouteImport } from './routes/dashboard.earnings'
import { Route as DashboardCoursesRouteImport } from './routes/dashboard.courses'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard.calendar'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as CoursesSlugRouteImport } from './routes/courses.$slug'
import { Route as BookTutorIdRouteImport } from './routes/book.$tutorId'
import { Route as AdminReviewRouteImport } from './routes/admin.review'
import { Route as TutorCoursesIndexRouteImport } from './routes/tutor.courses.index'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard.settings.index'
import { Route as TutorSettingsAvailabilityRouteImport } from './routes/tutor.settings.availability'
import { Route as TutorCoursesNewRouteImport } from './routes/tutor.courses.new'
import { Route as DashboardSettingsVerificationRouteImport } from './routes/dashboard.settings.verification'
import { Route as TutorCoursesCourseIdEditRouteImport } from './routes/tutor.courses.$courseId.edit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const FindTutorRoute = FindTutorRouteImport.update({
  id: '/find-tutor',
  path: '/find-tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const TutorTutorIdRoute = TutorTutorIdRouteImport.update({
  id: '/tutor/$tutorId',
  path: '/tutor/$tutorId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsVerificationRoute = SettingsVerificationRouteImport.update({
  id: '/settings/verification',
  path: '/settings/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIdRoute = SessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PathwiseDemoRoute = PathwiseDemoRouteImport.update({
  id: '/pathwise/demo',
  path: '/pathwise/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTutorRoute = OnboardingTutorRouteImport.update({
  id: '/onboarding/tutor',
  path: '/onboarding/tutor',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStudentRoute = OnboardingStudentRouteImport.update({
  id: '/onboarding/student',
  path: '/onboarding/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMessagesRoute = DashboardMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEarningsRoute = DashboardEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCoursesRoute = DashboardCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const CoursesSlugRoute = CoursesSlugRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookTutorIdRoute = BookTutorIdRouteImport.update({
  id: '/book/$tutorId',
  path: '/book/$tutorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin/review',
  path: '/admin/review',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorCoursesIndexRoute = TutorCoursesIndexRouteImport.update({
  id: '/tutor/courses/',
  path: '/tutor/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const TutorSettingsAvailabilityRoute =
  TutorSettingsAvailabilityRouteImport.update({
    id: '/tutor/settings/availability',
    path: '/tutor/settings/availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const TutorCoursesNewRoute = TutorCoursesNewRouteImport.update({
  id: '/tutor/courses/new',
  path: '/tutor/courses/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsVerificationRoute =
  DashboardSettingsVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const TutorCoursesCourseIdEditRoute =
  TutorCoursesCourseIdEditRouteImport.update({
    id: '/tutor/courses/$courseId/edit',
    path: '/tutor/courses/$courseId/edit',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/find-tutor': typeof FindTutorRoute
  '/matches': typeof MatchesRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/review': typeof AdminReviewRoute
  '/book/$tutorId': typeof BookTutorIdRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/onboarding/student': typeof OnboardingStudentRoute
  '/onboarding/tutor': typeof OnboardingTutorRoute
  '/pathwise/demo': typeof PathwiseDemoRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/settings/verification': typeof SettingsVerificationRoute
  '/tutor/$tutorId': typeof TutorTutorIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/dashboard/settings/verification': typeof DashboardSettingsVerificationRoute
  '/tutor/courses/new': typeof TutorCoursesNewRoute
  '/tutor/settings/availability': typeof TutorSettingsAvailabilityRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/tutor/courses/': typeof TutorCoursesIndexRoute
  '/tutor/courses/$courseId/edit': typeof TutorCoursesCourseIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/find-tutor': typeof FindTutorRoute
  '/matches': typeof MatchesRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/review': typeof AdminReviewRoute
  '/book/$tutorId': typeof BookTutorIdRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/onboarding/student': typeof OnboardingStudentRoute
  '/onboarding/tutor': typeof OnboardingTutorRoute
  '/pathwise/demo': typeof PathwiseDemoRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/settings/verification': typeof SettingsVerificationRoute
  '/tutor/$tutorId': typeof TutorTutorIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/dashboard/settings/verification': typeof DashboardSettingsVerificationRoute
  '/tutor/courses/new': typeof TutorCoursesNewRoute
  '/tutor/settings/availability': typeof TutorSettingsAvailabilityRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
  '/tutor/courses': typeof TutorCoursesIndexRoute
  '/tutor/courses/$courseId/edit': typeof TutorCoursesCourseIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/find-tutor': typeof FindTutorRoute
  '/matches': typeof MatchesRoute
  '/quiz': typeof QuizRoute
  '/reset-password': typeof ResetPasswordRoute
  '/roadmap': typeof RoadmapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/review': typeof AdminReviewRoute
  '/book/$tutorId': typeof BookTutorIdRoute
  '/courses/$slug': typeof CoursesSlugRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/courses': typeof DashboardCoursesRoute
  '/dashboard/earnings': typeof DashboardEarningsRoute
  '/dashboard/messages': typeof DashboardMessagesRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/onboarding/student': typeof OnboardingStudentRoute
  '/onboarding/tutor': typeof OnboardingTutorRoute
  '/pathwise/demo': typeof PathwiseDemoRoute
  '/sessions/$id': typeof SessionsIdRoute
  '/settings/verification': typeof SettingsVerificationRoute
  '/tutor/$tutorId': typeof TutorTutorIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/dashboard/settings/verification': typeof DashboardSettingsVerificationRoute
  '/tutor/courses/new': typeof TutorCoursesNewRoute
  '/tutor/settings/availability': typeof TutorSettingsAvailabilityRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/tutor/courses/': typeof TutorCoursesIndexRoute
  '/tutor/courses/$courseId/edit': typeof TutorCoursesCourseIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/find-tutor'
    | '/matches'
    | '/quiz'
    | '/reset-password'
    | '/roadmap'
    | '/sitemap.xml'
    | '/admin/review'
    | '/book/$tutorId'
    | '/courses/$slug'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/courses'
    | '/dashboard/earnings'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/onboarding/student'
    | '/onboarding/tutor'
    | '/pathwise/demo'
    | '/sessions/$id'
    | '/settings/verification'
    | '/tutor/$tutorId'
    | '/dashboard/'
    | '/sessions/'
    | '/dashboard/settings/verification'
    | '/tutor/courses/new'
    | '/tutor/settings/availability'
    | '/dashboard/settings/'
    | '/tutor/courses/'
    | '/tutor/courses/$courseId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/find-tutor'
    | '/matches'
    | '/quiz'
    | '/reset-password'
    | '/roadmap'
    | '/sitemap.xml'
    | '/admin/review'
    | '/book/$tutorId'
    | '/courses/$slug'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/courses'
    | '/dashboard/earnings'
    | '/dashboard/messages'
    | '/onboarding/student'
    | '/onboarding/tutor'
    | '/pathwise/demo'
    | '/sessions/$id'
    | '/settings/verification'
    | '/tutor/$tutorId'
    | '/dashboard'
    | '/sessions'
    | '/dashboard/settings/verification'
    | '/tutor/courses/new'
    | '/tutor/settings/availability'
    | '/dashboard/settings'
    | '/tutor/courses'
    | '/tutor/courses/$courseId/edit'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/demo'
    | '/find-tutor'
    | '/matches'
    | '/quiz'
    | '/reset-password'
    | '/roadmap'
    | '/sitemap.xml'
    | '/admin/review'
    | '/book/$tutorId'
    | '/courses/$slug'
    | '/dashboard/analytics'
    | '/dashboard/calendar'
    | '/dashboard/courses'
    | '/dashboard/earnings'
    | '/dashboard/messages'
    | '/dashboard/settings'
    | '/onboarding/student'
    | '/onboarding/tutor'
    | '/pathwise/demo'
    | '/sessions/$id'
    | '/settings/verification'
    | '/tutor/$tutorId'
    | '/dashboard/'
    | '/sessions/'
    | '/dashboard/settings/verification'
    | '/tutor/courses/new'
    | '/tutor/settings/availability'
    | '/dashboard/settings/'
    | '/tutor/courses/'
    | '/tutor/courses/$courseId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  FindTutorRoute: typeof FindTutorRoute
  MatchesRoute: typeof MatchesRoute
  QuizRoute: typeof QuizRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RoadmapRoute: typeof RoadmapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminReviewRoute: typeof AdminReviewRoute
  BookTutorIdRoute: typeof BookTutorIdRoute
  CoursesSlugRoute: typeof CoursesSlugRoute
  OnboardingStudentRoute: typeof OnboardingStudentRoute
  OnboardingTutorRoute: typeof OnboardingTutorRoute
  PathwiseDemoRoute: typeof PathwiseDemoRoute
  SessionsIdRoute: typeof SessionsIdRoute
  SettingsVerificationRoute: typeof SettingsVerificationRoute
  TutorTutorIdRoute: typeof TutorTutorIdRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  TutorCoursesNewRoute: typeof TutorCoursesNewRoute
  TutorSettingsAvailabilityRoute: typeof TutorSettingsAvailabilityRoute
  TutorCoursesIndexRoute: typeof TutorCoursesIndexRoute
  TutorCoursesCourseIdEditRoute: typeof TutorCoursesCourseIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-tutor': {
      id: '/find-tutor'
      path: '/find-tutor'
      fullPath: '/find-tutor'
      preLoaderRoute: typeof FindTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/tutor/$tutorId': {
      id: '/tutor/$tutorId'
      path: '/tutor/$tutorId'
      fullPath: '/tutor/$tutorId'
      preLoaderRoute: typeof TutorTutorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/verification': {
      id: '/settings/verification'
      path: '/settings/verification'
      fullPath: '/settings/verification'
      preLoaderRoute: typeof SettingsVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$id': {
      id: '/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof SessionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pathwise/demo': {
      id: '/pathwise/demo'
      path: '/pathwise/demo'
      fullPath: '/pathwise/demo'
      preLoaderRoute: typeof PathwiseDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/tutor': {
      id: '/onboarding/tutor'
      path: '/onboarding/tutor'
      fullPath: '/onboarding/tutor'
      preLoaderRoute: typeof OnboardingTutorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/student': {
      id: '/onboarding/student'
      path: '/onboarding/student'
      fullPath: '/onboarding/student'
      preLoaderRoute: typeof OnboardingStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/messages': {
      id: '/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof DashboardMessagesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/earnings': {
      id: '/dashboard/earnings'
      path: '/earnings'
      fullPath: '/dashboard/earnings'
      preLoaderRoute: typeof DashboardEarningsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/courses': {
      id: '/dashboard/courses'
      path: '/courses'
      fullPath: '/dashboard/courses'
      preLoaderRoute: typeof DashboardCoursesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$tutorId': {
      id: '/book/$tutorId'
      path: '/book/$tutorId'
      fullPath: '/book/$tutorId'
      preLoaderRoute: typeof BookTutorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review': {
      id: '/admin/review'
      path: '/admin/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/courses/': {
      id: '/tutor/courses/'
      path: '/tutor/courses'
      fullPath: '/tutor/courses/'
      preLoaderRoute: typeof TutorCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/tutor/settings/availability': {
      id: '/tutor/settings/availability'
      path: '/tutor/settings/availability'
      fullPath: '/tutor/settings/availability'
      preLoaderRoute: typeof TutorSettingsAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutor/courses/new': {
      id: '/tutor/courses/new'
      path: '/tutor/courses/new'
      fullPath: '/tutor/courses/new'
      preLoaderRoute: typeof TutorCoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/verification': {
      id: '/dashboard/settings/verification'
      path: '/verification'
      fullPath: '/dashboard/settings/verification'
      preLoaderRoute: typeof DashboardSettingsVerificationRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/tutor/courses/$courseId/edit': {
      id: '/tutor/courses/$courseId/edit'
      path: '/tutor/courses/$courseId/edit'
      fullPath: '/tutor/courses/$courseId/edit'
      preLoaderRoute: typeof TutorCoursesCourseIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardSettingsRouteChildren {
  DashboardSettingsVerificationRoute: typeof DashboardSettingsVerificationRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsVerificationRoute: DashboardSettingsVerificationRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardCoursesRoute: typeof DashboardCoursesRoute
  DashboardEarningsRoute: typeof DashboardEarningsRoute
  DashboardMessagesRoute: typeof DashboardMessagesRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardCoursesRoute: DashboardCoursesRoute,
  DashboardEarningsRoute: DashboardEarningsRoute,
  DashboardMessagesRoute: DashboardMessagesRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  FindTutorRoute: FindTutorRoute,
  MatchesRoute: MatchesRoute,
  QuizRoute: QuizRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RoadmapRoute: RoadmapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminReviewRoute: AdminReviewRoute,
  BookTutorIdRoute: BookTutorIdRoute,
  CoursesSlugRoute: CoursesSlugRoute,
  OnboardingStudentRoute: OnboardingStudentRoute,
  OnboardingTutorRoute: OnboardingTutorRoute,
  PathwiseDemoRoute: PathwiseDemoRoute,
  SessionsIdRoute: SessionsIdRoute,
  SettingsVerificationRoute: SettingsVerificationRoute,
  TutorTutorIdRoute: TutorTutorIdRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  TutorCoursesNewRoute: TutorCoursesNewRoute,
  TutorSettingsAvailabilityRoute: TutorSettingsAvailabilityRoute,
  TutorCoursesIndexRoute: TutorCoursesIndexRoute,
  TutorCoursesCourseIdEditRoute: TutorCoursesCourseIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
